apiVersion: v1
kind: Secret
metadata:
  name: fastapi-secrets
type: Opaque
data:
  SECRET_KEY: c29tZXNlY3JldA==  # Para esta demo, queda hardcodeada en el código, pero debería configurarse en aws secrets manager.
